---
title: "CD8 map - test projection of external data"
author: "Paul Gueguen, Massimo Anreatta, and Santiago  Carmona"
date: "`r format(Sys.Date(),'%e de %B, %Y')`"
output: 
  rmdformats::downcute:
    lightbox: true
    thumbnails: false
    self_contained: true
    gallery: true
    code_folding: show
  pkgdown:
    as_is: true
---

```{r, include=FALSE, fig.width=16, fig.height=12}
library(renv)
renv::restore()
library(Seurat)
library(ggplot2)
library(scGate)
library(SignatuR)
library(dplyr)
library(ProjecTILs)
options(future.globals.maxSize= 5000*1024^2)
```

# Read in reference

```{r}
ref.path <- "~/Dropbox/CSI/Datasets/projectTils/CD8T_human_ref_v0.2_ds.rds"
ref <- readRDS(ref.path)

palette <- ref@misc$atlas.palette

DimPlot(ref, cols=palette, label = T) + theme(aspect.ratio = 1)
```

# Read in query data
```{r}
#List of datasets (CD8T only)
path_cache <- "./cache/"
cache_filename <- paste0(path_cache,"Step6.seurat.list.NickB.v0.4.CD8T.rds")

query.list <- readRDS(cache_filename)

```

Split by samples used for reference, and remaining samples
```{r}
in.ref <- unique(ref$SampleLabel)
query.inref <- query.list[in.ref]
query.inref <- lapply(query.inref, NormalizeData)

not.ref <- setdiff(names(query.list), in.ref)

query.external <- query.list[not.ref]
```

#Project new data
```{r}
query.projected <- Run.ProjecTILs(query.inref, ref=ref, ncores=8)
```

```{r}
plot.projection(ref, query=query.projected[[1]], linesize = 0.5, pointsize = 0.5)
```

```{r fig.height=4}
genes4radar <- c('SELL', "TCF7", "CCR7","IL7R","GZMA","GZMK",
           "FGFBP2",'FCGR3A','XCL1',"XCL2","CD200","CRTAM","GNG4","TOX",'PDCD1',"HAVCR2",
           "GZMB","PRF1","LAG3",'KLRB1','TRAV1-2')
plot.states.radar(ref, query = query.projected[1:5], genes4radar = genes4radar)
```

Find markers for unsupervised clusters
```{r}
query.merged <- Reduce(merge.Seurat.embeddings, query.projected)
Idents(query.merged) <- "functional.cluster"
DefaultAssay(query.merged) <- "RNA"
set.seed(1234)

#subtype.markers <- FindAllMarkers(query.merged, only.pos = T,  assay = 'RNA', min.pct = 0.3, min.diff.pct = 0.2)
subtype.markers <- FindAllMarkers(query.merged, only.pos = T,  assay = 'RNA', min.pct = 0.3,
                                  min.diff.pct = 0.2, features = ref@assays$integrated@var.features)


subtype.markers.genes <- subtype.markers |> dplyr::group_by(cluster) |> dplyr::top_n(n = 15, wt = abs(avg_log2FC))

for (i in levels(query.merged@active.ident)) {
    print(subset(subtype.markers.genes, cluster==i))
} 

genes.use <- unique(subtype.markers.genes$gene)
```

```{r fig.height=3.5, fig.width=4.5}
source("functions.R")
library(pheatmap)


h <- make.heatmap(query.merged, cluster.col = 'functional.cluster',  dataset.col="Tissue",
                  dataset.tissue = "Type", assay = "integrated", genes = genes.use, min.cells=50,
                  cluster_genes = FALSE, cluster_samples = FALSE, method="ward.D2")
ggsave("plots/CD8T_heatmap_reprojected_unclustered.png", plot=h, height=12, width=15)

h <- make.heatmap(query.merged,cluster.col = 'functional.cluster',  dataset.col="Tissue",
                  dataset.tissue = "Type", assay = "integrated", genes = genes.use, min.cells=50,
                  cluster_genes = TRUE, cluster_samples = TRUE, method="ward.D2")
ggsave("plots/CD8T_heatmap_reprojected_clustered.png", plot=h, height=12, width=15)
```
Project the rest
```{r}
q <- query.external[c("LN22","LB9","HL2.3","HL3.2")]
q <- lapply(q, NormalizeData)

ext.proj <- lapply(q, function(x) {
  ProjecTILs.classifier(x, ref = ref, filter.cells = FALSE)
})

```

```{r}
s <- lapply(ext.proj, function(x){x@meta.data[,c("SampleLabel","functional.cluster")]})
stat <- Reduce(rbind, s)

tab <- table(stat$SampleLabel, stat$functional.cluster)
tab.norm <- tab/rowSums(tab)

df <- reshape2::melt(tab.norm)
colnames(df) <- c("Study","Subtype","Frequency")

palette <- ref@misc$atlas.palette

ggplot(df, aes(x = Study, y = Frequency, 
            fill = Subtype)) + geom_bar(stat = "identity") + 
            theme_bw() + scale_fill_manual(values = palette) +
            theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```

```{r fig.height=4}
genes4radar <- c('SELL', "TCF7", "CCR7","IL7R","GZMA","GZMK",
           "FGFBP2",'FCGR3A','XCL1',"XCL2","CD200","CRTAM","GNG4","TOX",'PDCD1',"HAVCR2",
           "GZMB","PRF1","LAG3",'KLRB1','TRAV1-2')
plot.states.radar(ref, query = ext.proj, genes4radar = genes4radar)
```

```{r}
tex <- subset(query.merged, subset=functional.cluster=="CD8.TEX")
DefaultAssay(tex) <- "RNA"
VlnPlot(tex, features=c("HAVCR2","PDCD1","LAG3","CXCL13"), group.by = "SampleLabel", pt.size = 0, ncol=2)
DefaultAssay(tex) <- "integrated"
VlnPlot(tex, features=c("HAVCR2","PDCD1","LAG3","CXCL13"), group.by = "SampleLabel", pt.size = 0, ncol=2)

```

```{r}
library(ggridges)
ls <- lapply(names(query.projected), function(n) {
  x <- query.projected[[n]]
  df <- as.data.frame(t(as.matrix(x@assays$RNA@data[c("CD3D","CD3E","LCK","CD8A"),])))
  df$Sample <- rep(n, nrow(df))
  df
})

dff <- Reduce(rbind, ls)  

ggplot(dff, aes(x = CD3D, y=Sample, fill = factor(stat(quantile)))) +
  stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE,
    quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis_d(name = "Quartiles")
ggplot(dff, aes(x = CD3E, y=Sample, fill = factor(stat(quantile)))) +
  stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE,
    quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis_d(name = "Quartiles")
ggplot(dff, aes(x = LCK, y=Sample, fill = factor(stat(quantile)))) +
  stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE,
    quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis_d(name = "Quartiles")
ggplot(dff, aes(x = CD8A, y=Sample, fill = factor(stat(quantile)))) +
  stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE,
    quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis_d(name = "Quartiles")
```


```{r}
library(scran)
renorm <- lapply(query.projected, function(x) {
  sce <- as.SingleCellExperiment(x, assay = "RNA")
  clusters <- quickCluster(sce, assay.type = "counts")
  sce <- computeSumFactors(sce, clusters=clusters)
  sce <- logNormCounts(sce)
  
  x@assays$RNA@data <- logcounts(sce, size.factors = sizeFactors(sce))
  x
})
```

```{r}
library(ggridges)
ls <- lapply(names(renorm), function(n) {
  x <- renorm[[n]]
  df <- as.data.frame(t(x@assays$RNA@data[c("CD3D","CD3E","LCK","CD8A"),]))
  df$Sample <- rep(n, nrow(df))
  df
})

dff <- Reduce(rbind, ls)  

ggplot(dff, aes(x = CD3D, y=Sample, fill = factor(stat(quantile)))) +
  stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE,
    quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis_d(name = "Quartiles")
ggplot(dff, aes(x = CD3E, y=Sample, fill = factor(stat(quantile)))) +
  stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE,
    quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis_d(name = "Quartiles")
ggplot(dff, aes(x = LCK, y=Sample, fill = factor(stat(quantile)))) +
  stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE,
    quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis_d(name = "Quartiles")
ggplot(dff, aes(x = CD8A, y=Sample, fill = factor(stat(quantile)))) +
  stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE,
    quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis_d(name = "Quartiles")
```

Bring all datasets to the same global mean normalized value
```{r}
means <- lapply(query.projected, function(x) {
  mean(x@assays$RNA@data)
})  

#target mean expression
target <- 0.1
correction_factor <- target/unlist(means)

renorm <- lapply(names(query.projected), function(n) {
  
  x <- query.projected[[n]]
  x@assays$RNA@data <- x@assays$RNA@data * correction_factor[n]
  x
})
names(renorm) <- names(query.projected)
```


```{r}
library(ggridges)
ls <- lapply(names(renorm), function(n) {
  x <- renorm[[n]]
  df <- as.data.frame(t(x@assays$RNA@data[c("CD3D","CD3E","LCK","CD8A"),]))
  df$Sample <- rep(n, nrow(df))
  df
})

dff <- Reduce(rbind, ls)  

ggplot(dff, aes(x = CD3D, y=Sample, fill = factor(stat(quantile)))) +
  stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE,
    quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis_d(name = "Quartiles")
ggplot(dff, aes(x = CD3E, y=Sample, fill = factor(stat(quantile)))) +
  stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE,
    quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis_d(name = "Quartiles")
ggplot(dff, aes(x = LCK, y=Sample, fill = factor(stat(quantile)))) +
  stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE,
    quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis_d(name = "Quartiles")
ggplot(dff, aes(x = CD8A, y=Sample, fill = factor(stat(quantile)))) +
  stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE,
    quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis_d(name = "Quartiles")
```

Find markers for unsupervised clusters
```{r}
query.merged <- Reduce(merge.Seurat.embeddings, renorm)
Idents(query.merged) <- "functional.cluster"
DefaultAssay(query.merged) <- "RNA"
set.seed(1234)

subtype.markers <- FindAllMarkers(query.merged, only.pos = T,  assay = 'RNA', min.pct = 0.2, min.diff.pct = 0.1)
#subtype.markers <- FindAllMarkers(query.merged, only.pos = T,  assay = 'RNA', min.pct = 0.3,
#                                  min.diff.pct = 0.2, features = ref@assays$integrated@var.features)


subtype.markers.genes <- subtype.markers |> dplyr::group_by(cluster) |> dplyr::top_n(n = 10, wt = abs(avg_log2FC))

for (i in levels(query.merged@active.ident)) {
    print(subset(subtype.markers.genes, cluster==i))
} 

genes.use <- unique(subtype.markers.genes$gene)
```

```{r fig.height=3.5, fig.width=4.5}
source("functions.R")
library(pheatmap)

genes.use <- c('SELL', "TCF7", "CCR7","IL7R","KLF2","S1PR1","GZMA","GZMK","CCL4",
           "FGFBP2",'FCGR3A','XCL1',"XCL2","CD200","CRTAM","GNG4","TOX",'PDCD1',"HAVCR2",
           "GZMB","PRF1","LAG3",'CXCL13','ENTPD1','KLRB1','TRAV1-2',"CEBPD","SLC4A10")


h <- make.heatmap(query.merged, cluster.col = 'functional.cluster',  dataset.col="Tissue",
                  dataset.tissue = "Type", assay = "RNA", genes = genes.use, min.cells=50,
                  cluster_genes = FALSE, cluster_samples = FALSE)

h <- make.heatmap(query.merged,cluster.col = 'functional.cluster',  dataset.col="Tissue",
                  dataset.tissue = "Type", assay = "RNA", genes = genes.use, min.cells=50,
                  cluster_genes = TRUE, cluster_samples = TRUE, method="ward.D2")
```


