---
title: "CD8 TIL integration with LIGER"
author: "Massimo Andreatta, and Santiago  Carmona"
date: "`r format(Sys.Date(),'%e de %B, %Y')`"
output: 
  rmdformats::downcute:
    lightbox: true
    thumbnails: false
    self_contained: true
    gallery: true
    code_folding: show
  pkgdown:
    as_is: true
---

```{r, include=FALSE, fig.width=16, fig.height=12}
library(renv)
#renv::restore()
library(Seurat)
library(ggplot2)
library(dplyr)
library(rliger)
#options(future.globals.maxSize= 5000*1024^2)
```

We start from object of high-quality cells and balanced datasets generated by 1-QC_CD8_atlas.Rmd.

# Set up parameters

```{r}
path_output <- "./out/"
npcs <- 50
seed <- 123
set.seed(seed)

# Setup color palette
mycols <- c('NaiveLike' = '#b7d2e0', 'CM' = '#da6f6f','EM'= '#72b28a','TEMRA' = '#e5bfaf', 'TPEX' = '#aca6e0' , 'TEX' ='#f5d39f', "MAIT" = '#fdbfd4')

mycols_scGate <- c('CD8_N' = '#b7d2e0', 'CD8_EM'= '#72b28a','CD8_TEMRA' = '#e5bfaf', 'CD8_TPEX' = '#aca6e0' , 'CD8_TEX' ='#f5d39f', "CD8_MAIT" = '#fdbfd4')
```

Only have to run the following once
```{r}
prepare_h5 <- T
merged_file <- "cache/CD8T_largescale_all_merged.rds"
```

# Load data

```{r}
if (prepare_h5) {
  seurat.all <- readRDS('cache/Seurat.list.Utility.v0.4_step7.rds')
  length(seurat.all)
  
  library(DropletUtils)
  library(rhdf5)
  
  seurat.all <- lapply(seurat.all, NormalizeData)
  seurat.all <- lapply(seurat.all, function(x){
    x$functional.cluster <- NA
    x
  })
  
  #Exclude small samples (<500 cells)
  tab <- unlist(lapply(seurat.all, ncol))
  pass <- names(tab)[tab > 500]
  seurat.all <- seurat.all[pass]
  
  n <- unlist(lapply(seurat.all, ncol))
  head(sort(n))
  
  merged <- merge(seurat.all[[1]], seurat.all[-1])
  saveRDS(merged, file=merged_file)
}
```


```{r}
if (prepare_h5) {
  seurat.all <- SplitObject(merged, split.by = "SampleLabel")
  #following https://github.com/welch-lab/liger/issues/211
  hdf5_files <- lapply(names(seurat.all), function(x) {
    paste0("h5_files/", x,".h5")
  })
  names(hdf5_files) <- names(seurat.all)
  
  # Initialize HDF5 files
  h5closeAll()
  for (i in 1:length(hdf5_files)){
    h5createFile(hdf5_files[[i]])
    h5createGroup(hdf5_files[[i]], "matrix")
    
    mat <- seurat.all[[i]]@assays$RNA@counts
    mat = as(mat, "CsparseMatrix")
    
    barcodes = mat@Dimnames[[2]]
    genes = mat@Dimnames[[1]]
    
    h5write(barcodes, file=hdf5_files[[i]], name="matrix/barcodes")
    h5createGroup(hdf5_files[[i]], file.path("matrix", "features"))
    h5write(genes, file=hdf5_files[[i]], name="matrix/features/name")
    h5write(dim(mat), file=hdf5_files[[i]], name="matrix/shape")
    # save x, i, p into h5 file
    h5createDataset(hdf5_files[[i]],"matrix/data",dims=length(mat@x),storage.mode="double", chunk = 500)
    h5write(mat@x, file=hdf5_files[[i]], name="matrix/data", index = list(1:length(mat@x)))
    h5createDataset(hdf5_files[[i]],"matrix/indices",dims=length(mat@i),storage.mode="integer", chunk = 500)
    h5write(mat@i, file=hdf5_files[[i]], name="matrix/indices",index = list(1:length(mat@i))) # already zero-indexed.
    h5createDataset(hdf5_files[[i]],"matrix/indptr",dims=length(mat@p),storage.mode="integer", chunk = 500)
    h5write(mat@p, file=hdf5_files[[i]], name="matrix/indptr",index = list(1:length(mat@p)))
    h5closeAll()
  }
}
```

Remove Seurat object
```{r}
if (exists(deparse(substitute(seurat.all)))) {rm(seurat.all)}
```

Prepare list for LIGER
```{r}
flist <- as.list(list.files("h5_files", full.names = T))
names(flist) <- sub(".*/([^/]+)\\.h5", "\\1", flist)

#reduce list for small-scale test
#flist <- flist[1:20]

to_int = rliger::createLiger(flist)
```

```{r}
to_int = rliger::normalize(to_int)
to_int = rliger::selectGenes(to_int, var.thresh = 0.2, do.plot = F)
to_int = rliger::scaleNotCenter(to_int)
```

Online iNMF
```{r}
to_int = rliger::online_iNMF(to_int, k = npcs, miniBatch_size = 5000, max.epochs = 5)
```

Align with quantile normalization
```{r}
to_int = quantile_norm(to_int)
```

Convert to Seurat
```{r}
merged <- readRDS(merged_file)

#use cells included in Liger object
cells.use <- rownames(to_int@cell.data)

merged <- subset(merged, cells=cells.use)

VariableFeatures(merged) <- to_int@var.genes

merged[["iNMF"]] <- CreateDimReducObject(
    embeddings = do.call(what = 'rbind', args = to_int@H),
    loadings = t(x = to_int@W),
    assay = "RNA",
    key = "iNMF_"
  )
```

# Dimensional reduction and plotting
```{r}
merged <- RunUMAP(merged, dims = 1:ncol(merged[["iNMF"]]), reduction = "iNMF")

DimPlot(merged, group.by = "SampleLabel") + theme(aspect.ratio=1) + NoLegend()
DimPlot(merged, group.by = "scGate_multi", cols=mycols_scGate) + theme(aspect.ratio=1)
```
Save results
```{r}
saveRDS(merged, "cache/liger_integrated_allsamples.rds")
```

Find clusters and markers
```{r}
merged <- FindNeighbors(merged, reduction="iNMF", dims = 1:npcs)
merged <- FindClusters(merged, resolution = 0.1)

p <- DimPlot(merged, reduction = "umap", group.by = "seurat_clusters", label = T) + theme(aspect.ratio = 1)
p
ggsave("plots/liger_largescale_integration_bycluster.pdf", plot=p, height=4, width=6)

table(merged$scGate_multi, merged$seurat_clusters)
```
```{r fig.width=12, fig.height=4}
DefaultAssay(merged) <- 'RNA'
genes <- c('SELL','LEF1',"S1PR1","IL7R", "TCF7", "CCR7",
           "LMNA","GZMA","GZMK","CCL4","FGFBP2",'FCGR3A','KLRG1',"GNLY",
           'XCL1',"XCL2","GNG4","CRTAM","TOX","CXCL13",'PDCD1',
           "CXCR6","GZMB","PRF1","CTLA4","LAG3","HAVCR2",'KLRB1','SLC4A10','TRAV1-2')

DotPlot(merged, features = genes, cols="RdBu", scale=T, col.max=1.5) +
  theme(axis.text.x = element_text(angle = 45, hjust=1))

ggsave("plots/liger_allsamples_dotplot.pdf", height=4, width=11)
```
