---
title: "CD8 TIL integration with LIGER"
author: "Massimo Andreatta, and Santiago  Carmona"
date: "`r format(Sys.Date(),'%e de %B, %Y')`"
output: 
  rmdformats::downcute:
    lightbox: true
    thumbnails: false
    self_contained: true
    gallery: true
    code_folding: show
  pkgdown:
    as_is: true
---

```{r, include=FALSE, fig.width=16, fig.height=12}
library(renv)
renv::restore()
library(Seurat)
library(ggplot2)
library(dplyr)
#options(future.globals.maxSize= 5000*1024^2)
```

We start from object of high-quality cells and balanced datasets generated by 1-QC_CD8_atlas.Rmd.

# Set up parameters

```{r}
path_output <- "./out/"
npcs <- 50
seed <- 123
set.seed(seed)
semisup=TRUE

# Setup color palette
mycols <- c('NaiveLike' = '#b7d2e0', 'CM' = '#da6f6f','EM'= '#72b28a','TEMRA' = '#e5bfaf', 'TPEX' = '#aca6e0' , 'TEX' ='#f5d39f', "MAIT" = '#fdbfd4')

mycols_scGate <- c('CD8_N' = '#b7d2e0', 'CD8_EM'= '#72b28a','CD8_TEMRA' = '#e5bfaf', 'CD8_TPEX' = '#aca6e0' , 'CD8_TEX' ='#f5d39f', "CD8_MAIT" = '#fdbfd4')
```

# Load data

```{r}
merged <- readRDS("cache/CD8T_unintegrated.rds")
table(merged$SampleLabel)
```

```{r}
library(rliger)
library(SeuratWrappers)

merged <- FindVariableFeatures(merged)
merged <- ScaleData(merged, split.by = "SampleLabel", do.center = FALSE)

merged <- RunOptimizeALS(merged, k = npcs, lambda = 5, split.by = "SampleLabel")
merged <- RunQuantileNorm(merged, split.by = "SampleLabel")
```

# Dimensional reduction and plotting
```{r}
merged <- RunUMAP(merged, dims = 1:ncol(merged[["iNMF"]]), reduction = "iNMF")

DimPlot(merged, group.by = "SampleLabel") + theme(aspect.ratio=1)
DimPlot(merged, group.by = "scGate_multi", cols=mycols_scGate) + theme(aspect.ratio=1)
```
```{r}
saveRDS(merged, file="cache/CD8T_liger.rds")
```
